name: saunf
description: "Time Tracking app for tasks"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Logic
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0

  # Network
  dio: ^5.4.3+1
  internet_connection_checker: ^1.0.0+1

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Utils
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cached_network_image: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11
  bloc_test: ^9.1.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
